### ISSUE TITLE
(funmooc) edit translation of headings on course-detail pages

### ISSUE THREAD

**Issue by jsfununivers** [openfun/fun-richie-site-factory#116]
## Edit translation of headings

Context:  Request of the department "Forma Pro" in order to adapt the syllabus to their training courses / needs

- `Ce que vous allez apprendre` -> ``Objectifs``
 
 - `A la fin de ce cours, vous saurez :`-> `À la fin de cette formation, vous serez capable de :`

- `Plan de cours `-> `Programme`

![Capture d’écran du 2023-09-08 16-21-40](https://github.com/openfun/fun-richie-site-factory/assets/138883136/6efce933-7ed2-45fd-a03d-0358929969db)
![Capture d’écran du 2023-09-08 16-22-33](https://github.com/openfun/fun-richie-site-factory/assets/138883136/bf90ec9c-609e-4a07-9075-49864d6a1065)

**Comment by sampaccoud** [comment]
Shouldn't these changes be done on an separate course template so that we can keep the current wording for moocs?
